apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nginx-dev
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/sriramch163/gitops-autopilot-lab.git
    targetRevision: HEAD
    path: apps/nginx-app

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
